import copy
import importlib

modname = "problem3"
try:
    module = importlib.import_module(modname)
    observe = getattr(module,"observe")
    probability_of = getattr(module,"probability_of")
    reset = getattr(module,"reset")
except Exception as e:
    print("Error loading module and/or function - check the names?")
    print("Error description: " + str(e))
    quit()

print("Case #1:")
reset()
observe(0)
observe(1)
observe(0)
observe(1)
observe(0)
observe(2)
observe(0)
observe(2)
observe(1)
observe(0)
print("Probability of 0 should be 0.5, your function returned: " + str(probability_of(0)))
print("Probability of 1 should be 0.3, your function returned: " + str(probability_of(1)))
print("Probability of 2 should be 0.2, your function returned: " + str(probability_of(2)))
print("Probability of 3 should be 0.0, your function returned: " + str(probability_of(3)))

print("Case #2:")
reset()
observe(0)
observe(4)
observe(4)
observe(0)
observe(0)
observe(4)
observe(4)
observe(4)
observe(0)
observe(0)
observe(0)
observe(4)
observe(0)
observe(4)
print("Probability of 0 should be 0.5, your function returned: " + str(probability_of(0)))
print("Probability of 4 should be 0.5, your function returned: " + str(probability_of(4)))
print("Probability of 1 should be 0.0, your function returned: " + str(probability_of(1)))

print("Case #3:")
reset()
observe(5)
print("Probability of 5 should be 1.0, your function returned: " + str(probability_of(5)))
print("Probability of 0 should be 0.0, your function returned: " + str(probability_of(0)))
